#package(default_visibility = ["//visibility:public"])
#
#cc_library(
#    name = "utils",
#    hdrs = [
#        ":attribute_utils.h",
#        ":system_utils.h",
#    ],
#    srcs = [
#        ":attribute_utils.cpp",
#        ":system_utils.cpp",
#    ],
#    target_compatible_with = [
#        "@platforms//cpu:arm64",
#        "@platforms//os:macos",
#    ],
#)
