package(default_visibility = ["//visibility:public"])
load("//tests/py/tools:pytest_defs.bzl", "pytest_test")

pytest_test(
    name = "test_basic_widgets",
    srcs = ["test_basic_widgets.py"],
    deps = ["//tests/py/tools:e2e_test_case_process"],
)