package(default_visibility = ["//visibility:public"])
load("@pytest_deps//:requirements.bzl", "requirement")

py_binary(
    name = "basic_widgets_case",
    srcs = ["basic_widgets_case.py"],
    deps = [requirement("pyside6")],
)