package(default_visibility = ["//visibility:public"])

#cc_library(
#    name = "screen_reader_impl_mac",
#    hdrs = [
#        ":screen_reader_impl_mac.h",
#    ],
#    srcs = [
#        ":screen_reader_impl_mac.cpp",
#    ],
#    deps = [
#        "//src/native/macos/utils:utils"
#    ],
#    target_compatible_with = [
#        "@platforms//cpu:arm64",
#        "@platforms//os:macos",
#    ],
#)

#cc_library(
#    name = "vwidget_generator",
#    hdrs = [
#        ":vwidget_generator.h",
#    ],
#    srcs = [
#        ":vwidget_generator.cpp",
#    ],
#    deps = [
#        "//src/native/macos/utils:utils"
#    ],
#    target_compatible_with = [
#        "@platforms//cpu:arm64",
#        "@platforms//os:macos",
#    ],
#)
