package(default_visibility = ["//visibility:public"])

load("@pybind11_bazel//:build_defs.bzl", "pybind_extension", "pybind_library")

pybind_library(
    name = "vwidget",
    srcs = [
        ":virtual_container_widget.cpp",
        ":virtual_widget.cpp",
    ],
    deps = [

    ],
)