package(default_visibility = ["//visibility:public"])

exports_files(
    [
        "virtual_button_widget.h",
        "virtual_menu_group_widget.h",
        "virtual_menu_item_widget.h",
        "virtual_root_widget.h",
        "virtual_text_field_widget.h",
        "virtual_text_widget.h",
        "virtual_group_widget.h",
        "virtual_unknown_widget.h",
        "virtual_window_widget.h",
    ]
)