package(default_visibility = ["//visibility:public"])

cc_library(
    name = "build_flags",
    hdrs = ["build_flags.h"],
)

cc_library(
    name = "types",
    hdrs = ["types.h"],
    deps = ["//src/base:build_flags"],
)
