name: Publish Pipeline
on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
        description: Version to release
      commit_hash:
        required: true
        type: string
        description: Commit hash to create release from
      live_run:
        default: false
        type: boolean
        description: Upload to PyPI (Unchecked will only upload to TestPyPI)

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    env:
      GITHUB_RELEASE_TAG: v${{ github.event.inputs.release_tag }}

    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup"

      - name: Download Wheels from Staging
        run: |
          mkdir -p /tmp/release
          bazel run //tools:download_wheels -- ${{ github.event.inputs.release_tag }} -w /tmp/release
          ls -lh /tmp/release

      - name: Create Archive Branch & Generate Release Note
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout ${{ github.event.inputs.commit_hash }}

          git checkout -b "archive/$GITHUB_RELEASE_TAG"
          git push origin "archive/$GITHUB_RELEASE_TAG" --force

          if git rev-parse "$GITHUB_RELEASE_TAG" >/dev/null 2>&1; then
            echo "Tag $GITHUB_RELEASE_TAG already exists, skipping."
          else
            git tag "$GITHUB_RELEASE_TAG"
            git push origin "$GITHUB_RELEASE_TAG" --force
          fi

      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ env.GITHUB_RELEASE_TAG }}
          tag: ${{ env.GITHUB_RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Wheels to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GITHUB_RELEASE_TAG }}
          name: Release ${{ env.GITHUB_RELEASE_TAG }}
          files: /tmp/release/*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Twine
        run: |
          pip install --upgrade twine

      - name: Upload to TestPyPI Staging
        if: ${{ github.event.inputs.live_run != 'true' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi /tmp/release/* 

      - name: Upload to PyPI Prod
        if: ${{ github.event.inputs.live_run == 'true' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload /tmp/release/* 
