change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'

template: |
  ## Changes

  $CHANGES
